version: "3"

services:
  api:
    build: api
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: redis:alpine
    container_name: redis
    restart: always
    volumes:
      - .data:/data
    ports:
      - 6379:6379